### ISSUE TITLE
[DEFECT] Multiple Instantiations of CAPEX in repetition

### ISSUE THREAD

**Issue by klfrick2** [idaholab/TEAL#19]
--------
Defect Description
--------

**Describe the defect**
When using the "Repetitions" block and placing the end of the repetitions prior to the end of the global project lifetime the code throws an additional "CAPEX" at the end of the repetitions. 

##### What did you expect to see happen?
I would expect the code to just end all values at the end of the repetitions. 

##### What did you see instead?
I saw an additional CAPEX produced. See Year 10 below. This is using a repetition line as follows.   
Life_time> 10 /Life_time>
Repetitions> 1 /Repetitions> 

With a global lifetime of 30. 

CashFlow INFO (proj c_fl): Computing PROJECT cash flow for CashFlow "CA" ...
CashFlow INFO (proj comp): Project Cashflow for Component "Batt" CashFlow "CA":
CashFlow INFO (proj comp): Year, Time-Adjusted Value
CashFlow INFO (proj comp):    0:  3.375000000e+02
CashFlow INFO (proj comp):    1:  0.000000000e+00
CashFlow INFO (proj comp):    2:  0.000000000e+00
CashFlow INFO (proj comp):    3:  0.000000000e+00
CashFlow INFO (proj comp):    4:  0.000000000e+00
CashFlow INFO (proj comp):    5:  0.000000000e+00
CashFlow INFO (proj comp):    6:  0.000000000e+00
CashFlow INFO (proj comp):    7:  0.000000000e+00
CashFlow INFO (proj comp):    8:  0.000000000e+00
CashFlow INFO (proj comp):    9:  0.000000000e+00
**CashFlow INFO (proj comp):   10:  3.375000000e+02**
CashFlow INFO (proj comp):   11:  0.000000000e+00
CashFlow INFO (proj comp):   12:  0.000000000e+00
CashFlow INFO (proj comp):   13:  0.000000000e+00
CashFlow INFO (proj comp):   14:  0.000000000e+00
CashFlow INFO (proj comp):   15:  0.000000000e+00
CashFlow INFO (proj comp):   16:  0.000000000e+00
CashFlow INFO (proj comp):   17:  0.000000000e+00
CashFlow INFO (proj comp):   18:  0.000000000e+00
CashFlow INFO (proj comp):   19:  0.000000000e+00
CashFlow INFO (proj comp):   20:  0.000000000e+00
CashFlow INFO (proj comp):   21:  0.000000000e+00
CashFlow INFO (proj comp):   22:  0.000000000e+00
CashFlow INFO (proj comp):   23:  0.000000000e+00
CashFlow INFO (proj comp):   24:  0.000000000e+00
CashFlow INFO (proj comp):   25:  0.000000000e+00
CashFlow INFO (proj comp):   26:  0.000000000e+00
CashFlow INFO (proj comp):   27:  0.000000000e+00
CashFlow INFO (proj comp):   28:  0.000000000e+00
CashFlow INFO (proj comp):   29:  0.000000000e+00
CashFlow INFO (proj comp):   30:  0.000000000e+00

##### Do you have a suggested fix for the development team?

**Describe how to Reproduce**
1.  Create a TEAL input with a global lifetime = 30
2.  Create  a repetitions of 1
3.  Life_time = 10
4.  Look in the Capex system after the run. (no extraneous values occurred with the recurring tag. 

**Screenshots and Input Files**
Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

**Platform (please complete the following information):**
 - OS: Windows 10 using GITBASH

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by alfoa** [comment]
@klfrick2 this is related to issue #20 right?
