### ISSUE TITLE
[DEFECT] Documentation no longer builds on macOS

### ISSUE THREAD

**Issue by dylanjm** [idaholab/TEAL#51]
--------
Defect Description
--------

**Describe the defect**

##### What did you expect to see happen?

I imagine due to the recent change in module structure in RAVEN and related plugins, we are now seeing the documentation fail to build due to relative import errors. 

Here is the error I get when trying to run `make` on macOS:

```
chmod u+x script/copy_tex.sh
script/copy_tex.sh
python script/generate_user_manual.py
Traceback (most recent call last):
  File "/Users/mcdodj/Documents/projects/TEAL/doc/script/generate_user_manual.py", line 9, in <module>
    import collect_tex
  File "/Users/mcdodj/Documents/projects/TEAL/doc/script/collect_tex.py", line 15, in <module>
    import CashFlows
  File "/Users/mcdodj/Documents/projects/TEAL/src/CashFlows.py", line 32, in <module>
    from ..src import Amortization
ImportError: attempted relative import with no known parent package
make: *** [populate] Error 1
```

**Describe how to Reproduce**
1.  Run `make` on macOS
2. 
3. 
4. 

**Screenshots and Input Files**
Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

**Platform (please complete the following information):**
 - Version: [e.g. 22]
 - Dependencies Installation: [CONDA or PIP]

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [ ] 1. Is it tagged with a type: defect or task?
- [ ] 2. Is it tagged with a priority: critical, normal or minor?
- [ ] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by worseliz** [comment]
The documentation also will not compile on Windows. Terminating error is:

C:\...\raven\plugins\HERON\doc\sqa\srs_rtr_combined>DEL /Q *.aux *.log *.out *.pdf *.toc ..\srs\requirements.tex ..\rtr\traceability_matrix.tex
Could Not Find C:\...\raven\plugins\HERON\doc\sqa\rtr\traceability_matrix.tex

**Comment by joshua-cogliati-inl** [comment]
Okay, `TEAL/doc/script/collect_tex.py` does the CashFlows import wrong for the new way of doing paths.  I'll see if I can fix it quickly.

**Comment by PaulTalbot-INL** [comment]
The work in #62 hopefully solves this; however, automated tests don't cover building the documentation, so this should be checked on OSX, Windows, and Linux with the changes before closing this issue.
