### ISSUE TITLE
[DEFECT] Amortization Cashflows Not Included in NPV Search

### ISSUE THREAD

**Issue by GabrielSoto-INL** [idaholab/TEAL#73]
--------
Defect Description
--------

This is for a very specific configuration: If conducting an NPV search where the `mult_target` is a one-time cashflow (e.g., CAPEX) **and** it includes depreciation, the two depreciation cashflows that are generated should be included as multiplier targets but are currently not. This is needs to happen because the two depreciation cashflows are dependent on the original `mult_target` cashflow as a driver. 

##### What did you see instead?
When stepping through the `npvSearch` method in `TEAL/src/main.py` via debugger, only the one-time cashflow is included in the `multiplied` terms when selected as a `mult_target`. (This was done through a HERON inner.xml script). 

##### Do you have a suggested fix for the development team?
When calling `_createDepreciation` the two cashflows should have a `mult_target` entry in the initParams that match the original cashflow's `mult_target` value. 

**Describe how to Reproduce**
1. 
2. 
3. 
4. 

**Screenshots and Input Files**
Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

**Platform (please complete the following information):**
 - Version: [e.g. 22]
 - Dependencies Installation: [CONDA or PIP]

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by PaulTalbot-INL** [comment]
Do you have access to posting on the discussion board about this change? While it is a niche case, it may have led to some errors in previous NPV search calculations.

Approved to close via #74.
