### ISSUE TITLE
[TASK] Support numpy 1.24

### ISSUE THREAD

**Issue by joshua-cogliati-inl** [idaholab/TEAL#89]
--------
Issue Description
--------

When running TEAL with numpy 1.24 the following error is possible:
```
Traceback (most recent call last):
  File "/home/civet/civet/build_0/raven/plugins/TEAL/tests/PyomoTest.py", line 273, in <module>
    metrics = RunCashFlow.run(tealSettings, [generator, market], {}, pyomoVar=True) # Past version was pyomoChk
  File "/home/civet/civet/build_0/raven/plugins/TEAL/src/main.py", line 652, in run
    lifeCf = componentLifeCashflow(comp, cf, variables, lifetimeCashflows, projectLife, v=0, pyomoVar=pyomoVar)
  File "/home/civet/civet/build_0/raven/plugins/TEAL/src/main.py", line 207, in componentLifeCashflow
    results = cf.calculateCashflow(variables, lifetimeCashflows, comp.getLifetime()+1, v)
  File "/home/civet/civet/build_0/raven/plugins/TEAL/src/CashFlows.py", line 1105, in calculateCashflow
    need = self.loadFromVariables(need, variables, lifetimeCashflows, lifetime)
  File "/home/civet/civet/build_0/raven/plugins/TEAL/src/CashFlows.py", line 889, in loadFromVariables
    need = self.extendParameters(need, lifetime)
  File "/home/civet/civet/build_0/raven/plugins/TEAL/src/CashFlows.py", line 1089, in extendParameters
    toExtend[name] = np.array(listArray)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (6,) + inhomogeneous part.
```

Fixing TEAL to work with numpy 1.24 would be good.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
Issue closure checklist is good.
