### ISSUE TITLE
[DEFECT] TEAL will not calculate yearly cashflow if in same processor

### ISSUE THREAD

**Issue by JiaZhou-PU** [idaholab/TEAL#9]
--------
Defect Description
--------

**Describe the defect**

##### What did you expect to see happen?
While using the same processor calculating multiple denoise, if pass-through different drivers of same recurring type cashflow variable. the Cash flow will not be calculated again.

##### What did you see instead?
The recurring cash flow will take the cashflow calculated before.

##### Do you have a suggested fix for the development team?
remove the `if self._yearlyCashflow is None` in Cashflows.py

**Describe how to Reproduce**
1. 
2. 
3. 
4. 

**Screenshots and Input Files**
Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

**Platform (please complete the following information):**
 - Version: [e.g. 22]
 - Dependencies Installation: [CONDA or PIP]

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by PaulTalbot-INL** [comment]
Is it normal to change the driver multiple times for a single CashFlow? I'm curious what the use case for this is.

It may be that we need to clarify how these objects should be used in codes for developers.

**Comment by JiaZhou-PU** [comment]
This is why I want to discuss it. I understand that it might be redundant to calculate everything everytime, but the capex and recurring type do have this difference. For synthetic system calculation it do needs to recalcuate everything, not for other runs.

**Comment by joshua-cogliati-inl** [comment]
I don't think an email needs to be written. @JiaZhou-PU what do you think?

**Comment by wangcj05** [comment]
@JiaZhou-PU @PaulTalbot-INL @alfoa 
The changes by this CR breaks LOGOS plugins. The reason for that is LOGOS calculates the cash flows by itself and sends the calculated cash flows to TEAL for the NPV calculation. With the new changes, it forces TEAL to recompute the cash flows for each run, and the original computed cash flows will be overwritten. This actually blocks the option to let the user to provided already calculated cashflows. To me, I think it is better to keep this option.
